<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\ClinicVets.Core\ClinicVets.Core.csproj" />
    <ProjectReference Include="..\ClinicVets.Data\ClinicVets.Data.csproj" />
    <ProjectReference Include="..\ClinicVets.g1\ClinicVets.g1.csproj" />
    <ProjectReference Include="..\ClinicVets.g2\ClinicVets.g2.csproj" />
    <ProjectReference Include="..\ClinicVets.g3\ClinicVets.g3.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

</Project>